#!/usr/bin/env bash
# Post-install configuration script for Linux Mint on Minix Z83-4
# Target: headless motion surveillance system
# Usage: sudo ./minix_z83_postinstall.sh [--debug] [--help]

set -euo pipefail

# ─────────────────────────────────────────────
# Flags
# ─────────────────────────────────────────────
DEBUG=false
ASSUME_YES=false
FORCE=false
LOG_FILE=""

usage() {
    cat <<EOF
Usage: sudo $(basename "$0") [OPTIONS]

Post-install script for Linux Mint on the Minix Z83-4 mini PC.
Configures the system for headless operation as a motion surveillance node.

OPTIONS:
  -h, --help    Show this help message and exit
  -d, --debug   Print each step before executing it
  -y, --yes     Assume "yes" to all prompts (non-interactive mode).
                A single up-front summary still requires acknowledgement
                unless --force is also supplied.
      --force   Skip the up-front change summary acknowledgement.
                Combined with --yes, runs the entire script unattended.

WHAT THIS SCRIPT DOES:
  1. Installs packages from the package list (edit PACKAGES array below)
  2. Applies additional system tweaks (edit TWEAKS section below)
  3. eMMC preservation: disables swap, noatime, tmpfs mounts, volatile journal,
     log rotation, core dump suppression, write-back tuning
  4. Fixes audio buffering via a PipeWire override config
  5. Installs the Broadcom WiFi firmware for the BCM43455 adapter
  6. Sets the CPU frequency governor to 'performance'
  7. Enables Intel P-state active mode via GRUB kernel parameter
  8. Configures rsyslog to forward logs to a remote syslog host and/or USB
     storage, with the option to disable local filesystem logging entirely
  9. Installs motionEye (pip bootstrap → pip.conf → pip install → motioneye_init)
     and verifies the web UI is reachable on port 8765
 10. Disables LightDM and stops desktop/display services for headless operation
     (refuses to run if SSH is not reachable on port 22)

Must be run as root (sudo).
EOF
    exit 0
}

for arg in "$@"; do
    case "$arg" in
        -h|--help)  usage ;;
        -d|--debug) DEBUG=true ;;
        -y|--yes)   ASSUME_YES=true ;;
        --force)    FORCE=true ;;
        *) echo "Unknown option: $arg" >&2; usage ;;
    esac
done

# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────
debug() { $DEBUG && echo "[DEBUG] $*"; }

confirm() {
    local prompt="$1"
    if $ASSUME_YES; then
        echo "$prompt [y/N] y   (auto-confirmed via --yes)"
        return 0
    fi
    local response
    read -r -p "$prompt [y/N] " response
    [[ "$response" =~ ^[Yy]$ ]]
}

require_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "ERROR: This script must be run as root. Use: sudo $0" >&2
        exit 1
    fi
}

# Exits the script with a formatted error banner. Args: title, line1, [line2...]
hard_stop() {
    local title="$1"; shift
    echo "" >&2
    echo "  ╔═══════════════════════════════════════════════════════════════╗" >&2
    printf  "  ║  %-61s  ║\n" "!! HARD STOP — ${title} !!" >&2
    echo "  ╠═══════════════════════════════════════════════════════════════╣" >&2
    for line in "$@"; do
        printf "  ║  %-61s  ║\n" "$line" >&2
    done
    echo "  ╚═══════════════════════════════════════════════════════════════╝" >&2
    echo "" >&2
    exit 1
}

preflight_check() {
    echo ""
    echo "--- Pre-flight: system validation ---"

    # ── Check 1: apt package lists exist and are less than 24 hours old ─────
    # /var/cache/apt/pkgcache.bin is regenerated by every successful apt update.
    local cache="/var/cache/apt/pkgcache.bin"

    if [[ ! -f "$cache" ]]; then
        hard_stop "apt update has never been run" \
            "No apt package cache found. The system must be fully" \
            "updated before this script is permitted to run." \
            "" \
            "Please run these commands and review all output carefully:" \
            "  sudo apt update" \
            "  sudo apt upgrade" \
            "" \
            "Then re-run this script."
    fi

    local cache_age=$(( $(date +%s) - $(stat -c %Y "$cache") ))
    local max_age=86400  # 24 hours

    if [[ "$cache_age" -gt "$max_age" ]]; then
        local hours=$(( cache_age / 3600 ))
        hard_stop "apt package lists are stale" \
            "The package cache is ${hours}h old (limit: 24h)." \
            "Run a fresh update/upgrade and review all output carefully:" \
            "" \
            "  sudo apt update" \
            "  sudo apt upgrade" \
            "" \
            "Then re-run this script."
    fi

    # ── Check 2: zero packages pending upgrade ───────────────────────────────
    local pending
    pending=$(apt list --upgradable 2>/dev/null | grep -c '\[upgradable' || true)

    if [[ "$pending" -gt 0 ]]; then
        hard_stop "system has ${pending} pending upgrade(s)" \
            "${pending} package(s) are waiting to be upgraded." \
            "A full upgrade must be completed and reviewed by you" \
            "before this script is permitted to run." \
            "" \
            "  sudo apt upgrade" \
            "" \
            "Review all changes, then re-run this script."
    fi

    # ── Check 3: internet connectivity (apt, pip, get-pip.py all need it) ───
    if ! ping -c 1 -W 2 1.1.1.1 >/dev/null 2>&1 \
       && ! ping -c 1 -W 2 8.8.8.8 >/dev/null 2>&1; then
        hard_stop "no internet connectivity detected" \
            "Cannot reach 1.1.1.1 or 8.8.8.8." \
            "This script needs internet to fetch apt packages, get-pip.py," \
            "and the motionEye Python package." \
            "" \
            "Verify network/DNS and re-run."
    fi

    # ── Check 4: required fstab-validation tool is present ──────────────────
    if ! command -v findmnt &>/dev/null; then
        hard_stop "findmnt is missing" \
            "fstab safety checks require 'findmnt' (util-linux)." \
            "Install it: sudo apt install util-linux"
    fi

    echo "    Package lists: fresh (updated within last 24h)"
    echo "    Pending upgrades: 0"
    echo "    Internet reachable: yes"
    echo "    fstab validator (findmnt): present"
    echo "    Pre-flight passed."
}

# ─────────────────────────────────────────────
# Safety helpers — fstab snapshot/rollback and SSH gating
# ─────────────────────────────────────────────

# Path to the most recent fstab snapshot taken by fstab_begin.
FSTAB_SNAPSHOT=""

# Take a snapshot of /etc/fstab before any edits in the current section.
fstab_begin() {
    FSTAB_SNAPSHOT="$(mktemp /tmp/fstab.snapshot.XXXXXX)"
    cp /etc/fstab "$FSTAB_SNAPSHOT"
    debug "fstab snapshot → $FSTAB_SNAPSHOT"
}

# Validate /etc/fstab via findmnt. On failure, restore the snapshot and
# hard_stop — protects the box from an unbootable fstab.
fstab_validate_or_rollback() {
    local label="${1:-fstab edit}"
    if findmnt --verify --tab-file /etc/fstab >/dev/null 2>&1; then
        debug "fstab validation passed: $label"
        rm -f "$FSTAB_SNAPSHOT"
        FSTAB_SNAPSHOT=""
        return 0
    fi

    echo "  !! fstab validation FAILED after: $label" >&2
    findmnt --verify --tab-file /etc/fstab >&2 || true

    if [[ -n "$FSTAB_SNAPSHOT" && -f "$FSTAB_SNAPSHOT" ]]; then
        cp "$FSTAB_SNAPSHOT" /etc/fstab
        echo "  !! /etc/fstab rolled back from snapshot." >&2
    fi
    hard_stop "fstab validation failed: ${label}" \
        "/etc/fstab was rolled back to its prior state." \
        "Inspect the change manually before re-running."
}

# True if sshd is active AND something is listening on port 22.
# Used as a gate before disabling the display manager so the operator
# does not lose all access to a headless machine.
verify_ssh_reachable() {
    local svc_ok=false
    if systemctl is-active --quiet ssh 2>/dev/null; then svc_ok=true; fi
    if systemctl is-active --quiet sshd 2>/dev/null; then svc_ok=true; fi
    $svc_ok || return 1

    if command -v ss &>/dev/null; then
        ss -tlnH 2>/dev/null | awk '{print $4}' | grep -qE '(^|:)22$' || return 1
    elif command -v netstat &>/dev/null; then
        netstat -tlnH 2>/dev/null | awk '{print $4}' | grep -qE '(^|:)22$' || return 1
    fi
    return 0
}

# Up-front summary of every destructive change. Honors --force to skip.
show_change_summary() {
    cat <<EOF

============================================================
 Minix Z83-4 Post-Install — Change Summary
============================================================
The script is about to perform the following changes. Review
them carefully. Type 'yes' (in full) to proceed, anything else
to abort.

  Section 1  — apt-get install ${#PACKAGES[@]} package(s)
  Section 2  — additional system tweaks (user-edited block)
  Section 3  — eMMC preservation:
               • disable swap, remove /swapfile
               • /etc/fstab: noatime on /, tmpfs for /tmp + /var/tmp
                 (validated with rollback on failure)
               • journald → volatile, 32 MB cap
               • logrotate, core dumps off, write-back tuning
               • disable apt periodic timers
  Section 4  — write /etc/pipewire/buffer.conf
  Section 5  — write /lib/firmware/brcm/brcmfmac43455-sdio.txt
  Section 6  — CPU governor → performance
  Section 7  — patch GRUB (intel_pstate=active), update-grub
               (rolled back if update-grub fails)
  Section 8  — configure rsyslog (remote/USB), optionally
               disable local file logging
  Section 9  — install motionEye via pip, verify port 8765
  Section 10 — disable LightDM and desktop services
               (REFUSED if SSH is not reachable on :22)

  Logfile:   ${LOG_FILE}
  Mode:      $($ASSUME_YES && echo "non-interactive (--yes)" || echo "interactive")

============================================================

EOF

    if $FORCE; then
        echo "  --force supplied: skipping summary acknowledgement."
        return 0
    fi

    local response
    read -r -p "Type 'yes' to proceed: " response
    if [[ "$response" != "yes" ]]; then
        hard_stop "aborted by user at summary prompt" \
            "No changes were made."
    fi
}

# ─────────────────────────────────────────────
# Bootstrap: root → logging → ERR trap → preflight
# ─────────────────────────────────────────────
require_root

# Self-logging: capture the entire run for post-mortem. Important because
# Section 3 makes journald volatile and disables local file logging later.
LOG_FILE="/root/minix-postinstall-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1
echo "Run transcript: $LOG_FILE"

# Clear failure reporting — tells the operator exactly where the script died.
trap 'rc=$?; echo "" >&2;
      echo "  !! SCRIPT FAILED — exit $rc at line $LINENO" >&2;
      echo "  !! command: $BASH_COMMAND" >&2;
      echo "  !! transcript: $LOG_FILE" >&2;
      echo "" >&2' ERR

preflight_check

# ─────────────────────────────────────────────
# SECTION 1 — PACKAGE INSTALLATION
# Add packages to install here. They will be installed in a single apt-get
# pass after an initial apt-get update. Leave the array empty to skip.
# ─────────────────────────────────────────────
PACKAGES=(
    # ── Core / TLS ──────────────────────────────────────────
    ca-certificates
    curl

    # ── Python build toolchain (required by motionEye) ──────
    python3
    python3-dev
    gcc

    # ── motionEye C-extension dependencies ──────────────────
    libjpeg62-dev
    libcurl4-openssl-dev
    libssl-dev

    # ── System utilities ────────────────────────────────────
    locate
    bpytop
    rsyslog             # needed by Section 9 (remote/USB logging)

    # ── Add further packages below this line ────────────────
    # openssh-server
    # ufw
    # cpufrequtils      # auto-installed by Section 6 if absent
)

install_packages() {
    if [[ ${#PACKAGES[@]} -eq 0 ]]; then
        echo "[packages] No packages listed — skipping."
        return
    fi

    echo ""
    echo "=== SECTION 1: Package Installation ==="
    echo "The following packages will be installed:"
    printf '  %s\n' "${PACKAGES[@]}"
    echo ""

    if confirm "Proceed with package installation?"; then
        debug "Running: apt-get update"
        apt-get update -qq

        debug "Running: apt-get install -y ${PACKAGES[*]}"
        apt-get install -y "${PACKAGES[@]}"
        echo "[packages] Done."
    else
        echo "[packages] Skipped by user."
    fi
}

# ─────────────────────────────────────────────
# SECTION 2 — ADDITIONAL SYSTEM TWEAKS
# Placeholder for one-off commands, sysctl settings, service enables, etc.
# Add shell statements here before the named sections below.
# ─────────────────────────────────────────────
additional_tweaks() {
    echo ""
    echo "=== SECTION 2: Additional System Tweaks ==="

    # ── INSERT TWEAKS BELOW ──────────────────────────────────────────────────

    # Example: set hostname
    # ------------------------------------------------
    # debug "Setting hostname to surveillance-node"
    # hostnamectl set-hostname surveillance-node

    # Example: disable IPv6
    # ------------------------------------------------
    # debug "Disabling IPv6 via sysctl"
    # echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    # sysctl -p

    # Example: disable IPv6, persistant across reboots
    # ------------------------------------------------
    # debug "Disabling IPv6 via sysctl"
    # echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.d/99-disable-ipv6.conf
    # echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.d/99-disable-ipv6.conf
    # sysctl -p /etc/sysctl.d/99-disable-ipv6.conf

    # ── END TWEAKS ───────────────────────────────────────────────────────────

    echo "[tweaks] Done."
}

# ─────────────────────────────────────────────
# SECTION 3 — eMMC PRESERVATION
# Minimises write amplification on the internal eMMC flash:
#   3a  Disable swap (swapoff, remove /swapfile, purge fstab entry)
#   3b  Add noatime,nodiratime to root filesystem mount options
#   3c  Mount /tmp and /var/tmp as tmpfs (RAM-backed, no flash writes)
#   3d  Configure systemd journal as volatile with a 32 MB cap
#   3e  Aggressive log rotation: daily, 3 generations, compressed
#   3f  Suppress core dumps
#   3g  Tune kernel write-back to batch dirty pages (fewer flush cycles)
#   3h  Disable apt periodic timer (daily index refreshes churn flash)
# ─────────────────────────────────────────────
configure_emmc() {
    echo ""
    echo "=== SECTION 3: eMMC Preservation ==="

    # Take a single snapshot of fstab; all 3a/3b/3c edits validate against it.
    fstab_begin

    # ── 3a: Disable swap ────────────────────────────────────────────────────
    echo "  [3a] Disabling swap..."
    debug "Running: swapoff -a"
    swapoff -a 2>/dev/null || true

    if grep -q '/swapfile' /etc/fstab; then
        debug "Removing /swapfile entry from /etc/fstab"
        sed -i '/\/swapfile/d' /etc/fstab
        echo "       /swapfile removed from fstab."
    fi

    if [[ -f /swapfile ]]; then
        if confirm "       Delete /swapfile from disk?"; then
            debug "Deleting /swapfile"
            rm -f /swapfile
            echo "       /swapfile deleted."
        fi
    fi

    debug "Setting vm.swappiness=0"
    echo "vm.swappiness=0" > /etc/sysctl.d/99-swappiness.conf
    sysctl -w vm.swappiness=0 >/dev/null

    # ── 3b: noatime on root filesystem ──────────────────────────────────────
    echo "  [3b] Adding noatime,nodiratime to root mount..."
    if grep -E '^\S+\s+/\s' /etc/fstab | grep -q 'noatime'; then
        echo "       noatime already present — skipping."
    else
        debug "Patching root mount options via awk"
        # Write to /run (always tmpfs) — avoids any chance of clobber on /tmp
        # before /tmp's tmpfs mount is active.
        local tmpf
        tmpf="$(mktemp /run/fstab.XXXXXX 2>/dev/null || mktemp)"
        awk '$2=="/" && !/noatime/ {
            $4 = $4 ",noatime,nodiratime"
        } {print}' /etc/fstab > "$tmpf"
        mv "$tmpf" /etc/fstab
        echo "       noatime,nodiratime added to root mount."
    fi

    # ── 3c: tmpfs for /tmp and /var/tmp ─────────────────────────────────────
    echo "  [3c] Adding tmpfs mounts for /tmp and /var/tmp..."
    if ! grep -qE 'tmpfs\s+/tmp\s' /etc/fstab; then
        echo "tmpfs  /tmp      tmpfs  defaults,nosuid,nodev,noatime,size=128M  0  0" >> /etc/fstab
        echo "       tmpfs /tmp  added to fstab."
    else
        echo "       tmpfs /tmp  already present — skipping."
    fi

    if ! grep -qE 'tmpfs\s+/var/tmp\s' /etc/fstab; then
        echo "tmpfs  /var/tmp  tmpfs  defaults,nosuid,nodev,noatime,size=64M   0  0" >> /etc/fstab
        echo "       tmpfs /var/tmp  added to fstab."
    else
        echo "       tmpfs /var/tmp  already present — skipping."
    fi

    # Validate everything we just wrote; roll back on failure.
    fstab_validate_or_rollback "Section 3 (swap/noatime/tmpfs)"
    echo "       fstab validated."

    # ── 3d: Volatile systemd journal, 32 MB cap ──────────────────────────────
    echo "  [3d] Configuring systemd journal (volatile, 32 MB)..."
    local jdir="/etc/systemd/journald.conf.d"
    debug "Creating $jdir"
    mkdir -p "$jdir"
    cat > "$jdir/99-emmc.conf" <<'EOF'
[Journal]
Storage=volatile
RuntimeMaxUse=32M
Compress=yes
EOF
    debug "Restarting systemd-journald"
    systemctl restart systemd-journald
    echo "       journald set to volatile storage."

    # ── 3e: Aggressive log rotation ─────────────────────────────────────────
    echo "  [3e] Configuring logrotate (daily, 3 generations, compressed)..."
    cat > /etc/logrotate.d/99-emmc <<'EOF'
/var/log/*.log /var/log/**/*.log {
    daily
    rotate 3
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
EOF
    echo "       logrotate override written."

    # ── 3f: Suppress core dumps ─────────────────────────────────────────────
    echo "  [3f] Disabling core dumps..."
    echo "kernel.core_pattern=/dev/null" > /etc/sysctl.d/99-no-coredumps.conf
    sysctl -w kernel.core_pattern=/dev/null >/dev/null
    local cddir="/etc/systemd/coredump.conf.d"
    mkdir -p "$cddir"
    cat > "$cddir/99-disable.conf" <<'EOF'
[Coredump]
Storage=none
ProcessSizeMax=0
EOF
    echo "       Core dumps suppressed."

    # ── 3g: Kernel write-back tuning ────────────────────────────────────────
    echo "  [3g] Tuning kernel write-back parameters..."
    cat > /etc/sysctl.d/99-emmc-writeback.conf <<'EOF'
# Batch dirty pages longer before flushing to reduce flash write cycles
vm.dirty_writeback_centisecs = 1500
vm.dirty_expire_centisecs    = 3000
vm.dirty_ratio               = 40
vm.dirty_background_ratio    = 10
EOF
    sysctl -p /etc/sysctl.d/99-emmc-writeback.conf >/dev/null
    echo "       Write-back tuning applied."

    # ── 3h: Disable apt periodic timers ─────────────────────────────────────
    echo "  [3h] Disabling apt periodic timers..."
    for timer in apt-daily.timer apt-daily-upgrade.timer; do
        if systemctl list-unit-files 2>/dev/null | grep -q "^${timer}"; then
            debug "Disabling $timer"
            systemctl disable "$timer" 2>/dev/null || true
            systemctl stop    "$timer" 2>/dev/null || true
            echo "       $timer disabled."
        fi
    done

    echo "[emmc] eMMC preservation complete."
}

# ─────────────────────────────────────────────
# SECTION 4 — AUDIO: PipeWire buffer config
# Creates /etc/pipewire/buffer.conf with pulse quantum/fragment overrides
# to reduce audio buffering artifacts.
# ─────────────────────────────────────────────
configure_audio() {
    echo ""
    echo "=== SECTION 4: Audio — PipeWire Buffer Config ==="

    local dir="/etc/pipewire"
    local file="$dir/buffer.conf"

    debug "Target file: $file"

    if [[ -f "$file" ]]; then
        echo "  $file already exists."
        if ! confirm "  Overwrite $file?"; then
            echo "[audio] Skipped."
            return
        fi
    fi

    debug "Creating directory $dir"
    mkdir -p "$dir"

    debug "Writing $file"
    cat > "$file" <<'EOF'
[pulse.properties]
pulse.min.quantum = 2048/48000
pulse.default.reg = 2048/48000
pulse.default.frag = 4096/48000
EOF

    echo "[audio] $file written."
}

# ─────────────────────────────────────────────
# SECTION 4 — WIFI: BCM43455 firmware file
# Writes brcmfmac43455-sdio.txt to /lib/firmware/brcm/ to activate the
# Broadcom WiFi adapter present in the Minix Z83-4.
# ─────────────────────────────────────────────
install_wifi_firmware() {
    echo ""
    echo "=== SECTION 5: WiFi — BCM43455 Firmware ==="

    local dir="/lib/firmware/brcm"
    local file="$dir/brcmfmac43455-sdio.txt"

    debug "Target file: $file"

    if [[ -f "$file" ]]; then
        echo "  $file already exists."
        if ! confirm "  Overwrite $file?"; then
            echo "[wifi] Skipped."
            return
        fi
    fi

    debug "Creating directory $dir"
    mkdir -p "$dir"

    debug "Writing $file"
    cat > "$file" <<'EOF'
#AP6255_NVRAM_V1.0_29052015
# *** Place this file in /lib/firmware/brcm and re-boot ***

NVRAMRev=$Rev: 498373 $
sromrev=11
vendid=0x14e4
devid=0x43ab
manfid=0x2d0
prodid=0x06e4
macaddr= cc:4b:73:43:05:b0
nocrc=1
boardtype=0x6e4
boardrev=0x1304
xtalfreq=37400
#boardflags: 5GHz eTR switch by default
#2.4GHz eTR switch by default
#bit1 for btcoex
boardflags=0x00080201
boardflags2=0x40000000
boardflags3=0x48200100
rxgains2gelnagaina0=0
rxgains2gtrisoa0=0
rxgains2gtrelnabypa0=0
rxgains5gelnagaina0=0
rxgains5gtrisoa0=0
rxgains5gtrelnabypa0=0
rxchain=1
txchain=1
aa2g=1
aa5g=1
tssipos5g=1
tssipos2g=1
femctrl=0
AvVmid_c0=0,157,1,126,1,126,1,126,1,126
pa2ga0=-112,6296,-662
pa2ga1=-165,3699,-515
pa5ga0=-143,6016,-683,-141,6013,-678,-137,5988,-670,-136,5982,-670
pa5ga1=-161,3544,-499,-166,3543,-497,-169,3569,-497,-171,3598,-498
itrsw=1
pdoffset2g40ma0=10
pdoffset40ma0=0xaaaa
pdoffset80ma0=0xaaaa
extpagain5g=2
extpagain2g=2
tworangetssi2g=1
tworangetssi5g=1
# LTECX flags
# WCI2
ltecxmux=0
ltecxpadnum=0x0504
ltecxfnsel=0x22
ltecxgcigpio=0x32

maxp2ga0=64
ofdmlrbw202gpo=0x0033
dot11agofdmhrbw202gpo=0x1553
mcsbw202gpo=0x99355533

maxp5ga0=80,82,76,77

mcsbw205glpo=0x99755000
mcsbw205gmpo=0x9df55000
mcsbw205ghpo=0x99855000

mcsbw405glpo=0xb8555000
mcsbw405gmpo=0xed955000
mcsbw405ghpo=0xd9755000

mcsbw805glpo=0xc8555000
mcsbw805gmpo=0xe9555000
mcsbw805ghpo=0xd9555000

swctrlmap_2g=0x00040004,0x00020002,0x00040004,0x010a02,0x1ff
swctrlmap_5g=0x00100010,0x00200020,0x00100010,0x010a02,0x2f4
swctrlmapext_5g=0x00000000,0x00000000,0x00000000,0x000000,0x000
swctrlmapext_2g=0x00000000,0x00000000,0x00000000,0x000000,0x000

vcodivmode=1
deadman_to=481500000
ed_thresh2g=-54
ed_thresh5g=-54

#muxenab=0x10
sd_gpout=0
sd_gpval=0

ccode=US
regrev=38
EOF

    echo "[wifi] $file written."
}

# ─────────────────────────────────────────────
# SECTION 5 — CPU: Performance governor
# Installs cpufrequtils, sets all cores to the 'performance' governor,
# and persists the setting via /etc/default/cpufrequtils.
# ─────────────────────────────────────────────
configure_cpu_governor() {
    echo ""
    echo "=== SECTION 6: CPU — Performance Governor ==="

    debug "Checking for cpufrequtils"
    if ! command -v cpufreq-set &>/dev/null; then
        echo "  cpufrequtils not found — installing..."
        debug "Running: apt-get install -y cpufrequtils"
        apt-get install -y cpufrequtils
    fi

    debug "Setting governor to performance for all CPUs"
    cpufreq-set -r -g performance
    echo "  Governor set to: performance"

    local conf="/etc/default/cpufrequtils"
    debug "Writing $conf"

    if [[ -f "$conf" ]]; then
        if grep -q '^GOVERNOR=' "$conf"; then
            debug "Updating existing GOVERNOR line in $conf"
            sed -i 's/^GOVERNOR=.*/GOVERNOR="performance"/' "$conf"
        else
            echo 'GOVERNOR="performance"' >> "$conf"
        fi
    else
        echo 'GOVERNOR="performance"' > "$conf"
    fi

    echo "[cpu] Governor persisted in $conf."
}

# ─────────────────────────────────────────────
# SECTION 6 — GPU/KERNEL: Intel P-state via GRUB
# Adds intel_pstate=active to GRUB_CMDLINE_LINUX_DEFAULT so the Intel GPU
# and CPU P-state driver runs in active (highest performance) mode.
# Runs update-grub after patching.
# ─────────────────────────────────────────────
configure_grub_pstate() {
    echo ""
    echo "=== SECTION 7: GRUB — Intel P-state ==="

    local grub_file="/etc/default/grub"
    debug "Reading $grub_file"

    if [[ ! -f "$grub_file" ]]; then
        echo "ERROR: $grub_file not found — skipping." >&2
        return
    fi

    if grep -q 'intel_pstate=active' "$grub_file"; then
        echo "  intel_pstate=active already present in $grub_file — skipping."
    else
        confirm "  Patch $grub_file to add intel_pstate=active and run update-grub?" || { echo "[grub] Skipped."; return; }

        debug "Backing up $grub_file to ${grub_file}.bak"
        cp "$grub_file" "${grub_file}.bak"

        debug "Injecting intel_pstate=active into GRUB_CMDLINE_LINUX_DEFAULT"
        # Append the parameter inside the existing quoted value
        sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*\)"/\1 intel_pstate=active"/' "$grub_file"

        echo "  Patched. Running update-grub..."
        debug "Running: update-grub"

        # update-grub failure can leave /boot/grub/grub.cfg malformed → unbootable.
        # Run inside an if-guard (bypasses set -e), restore on failure, then
        # try update-grub a second time to regenerate a known-good grub.cfg.
        if ! update-grub; then
            echo "  !! update-grub FAILED — restoring ${grub_file}.bak" >&2
            cp "${grub_file}.bak" "$grub_file"
            if ! update-grub; then
                hard_stop "update-grub failed twice" \
                    "Your grub config has been restored from backup but" \
                    "regeneration of /boot/grub/grub.cfg also failed." \
                    "DO NOT REBOOT until you have run 'sudo update-grub'" \
                    "manually and verified /boot/grub/grub.cfg is valid."
            fi
            hard_stop "update-grub failed (config rolled back)" \
                "/etc/default/grub restored; grub.cfg regenerated from backup."
        fi

        echo "[grub] Done. A reboot is required for this change to take effect."
    fi
}

# ─────────────────────────────────────────────
# SECTION 10 — HEADLESS: Disable LightDM and desktop services (RUNS LAST)
# Disables LightDM (display manager) and stops GUI-related services so the
# machine boots to a lean, headless runlevel. Motion and SSH remain active.
# ─────────────────────────────────────────────
disable_desktop() {
    echo ""
    echo "=== SECTION 10: Headless Mode — Disable Desktop Services ==="
    echo "  WARNING: This will disable the graphical desktop environment."
    echo "  The machine will boot to a text console only."
    echo ""

    # ── SSH gate: refuse to strand the operator on a headless box ───────────
    echo "  Verifying SSH is active and listening on :22 before continuing..."
    if ! verify_ssh_reachable; then
        echo "  !! SSH is NOT reachable on port 22." >&2
        echo "  !! Disabling the desktop now would leave the machine inaccessible." >&2
        echo "" >&2
        echo "  To fix: sudo apt install openssh-server && sudo systemctl enable --now ssh" >&2
        echo "" >&2
        if ! confirm "  Override the SSH gate and disable the desktop anyway?"; then
            echo "[headless] Skipped — SSH gate not satisfied."
            return 0
        fi
        echo "  !! Operator overrode SSH gate. Proceeding at your own risk."
    else
        echo "  SSH OK."
    fi

    confirm "  Disable LightDM and desktop services now?" || { echo "[headless] Skipped."; return; }

    # Set default boot target to multi-user (no GUI)
    debug "Setting default systemd target to multi-user.target"
    systemctl set-default multi-user.target

    # Disable and stop LightDM
    if systemctl list-unit-files | grep -q '^lightdm.service'; then
        debug "Disabling and stopping lightdm.service"
        systemctl disable lightdm.service
        systemctl stop lightdm.service 2>/dev/null || true
        echo "  lightdm disabled."
    else
        echo "  lightdm.service not found — skipping."
    fi

    # Disable other common desktop/display services if present
    local desktop_services=(
        "gdm.service"
        "gdm3.service"
        "sddm.service"
        "accounts-daemon.service"
        "colord.service"
        "cups.service"
        "bluetooth.service"
        "avahi-daemon.service"
    )

    for svc in "${desktop_services[@]}"; do
        if systemctl list-unit-files | grep -q "^${svc}"; then
            debug "Disabling $svc"
            systemctl disable "$svc" 2>/dev/null || true
            systemctl stop "$svc" 2>/dev/null || true
            echo "  $svc disabled."
        fi
    done

    echo "[headless] System configured for headless operation."
    echo "           Reboot to apply all changes."
}

# ─────────────────────────────────────────────
# SECTION 8 — LOGGING: Remote rsyslog and/or USB storage
#
# Forwards all syslog traffic off the eMMC to one or both destinations:
#   • Remote syslog server (rsyslog omfwd, TCP or UDP)
#   • USB-attached storage (block device → auto-mounted, rsyslog file output)
#
# Local filesystem logging (rsyslog 50-default.conf) can be disabled entirely
# once a remote/USB destination is confirmed, protecting eMMC longevity.
#
# Override any prompt by exporting these variables before running the script:
#   LOG_REMOTE_HOST     IP or hostname of the remote syslog receiver
#   LOG_REMOTE_PORT     UDP/TCP port (default: 514)
#   LOG_REMOTE_PROTO    "tcp" or "udp" (default: tcp)
#   LOG_USB_DEVICE      Block device path, e.g. /dev/sdb1
#   LOG_USB_MOUNT       Mount point (default: /mnt/usb-log)
#   LOG_DISABLE_LOCAL   Set to "true" to suppress the confirm prompt
# ─────────────────────────────────────────────
configure_logging() {
    echo ""
    echo "=== SECTION 8: Logging — Remote rsyslog / USB Storage ==="
    echo "  Goal: route all logs off the eMMC; optionally silence local writes."
    echo ""

    local remote_host="${LOG_REMOTE_HOST:-}"
    local remote_port="${LOG_REMOTE_PORT:-514}"
    local remote_proto="${LOG_REMOTE_PROTO:-tcp}"
    local usb_device="${LOG_USB_DEVICE:-}"
    local usb_mount="${LOG_USB_MOUNT:-/mnt/usb-log}"
    local disable_local="${LOG_DISABLE_LOCAL:-}"

    local do_remote=false
    local do_usb=false

    # ── 9a: Remote rsyslog forwarding ────────────────────────────────────────
    if confirm "  Configure remote rsyslog forwarding?"; then
        if [[ -z "$remote_host" ]]; then
            read -r -p "    Remote syslog host (IP or hostname): " remote_host
        fi

        if [[ -z "$remote_host" ]]; then
            echo "    No host entered — skipping remote forwarding."
        else
            do_remote=true
            echo "    Host:     $remote_host"
            echo "    Port:     $remote_port  (override: export LOG_REMOTE_PORT=<n>)"
            echo "    Protocol: $remote_proto  (override: export LOG_REMOTE_PROTO=tcp|udp)"

            # Legacy-style queue directives for broad rsyslog 8.x compatibility.
            # The in-memory queue buffers up to 10 000 messages if the remote is
            # temporarily unreachable; SaveOnShutdown is intentionally off to
            # avoid writing a queue spool file to eMMC.
            local proto_flag="@@"                       # TCP (reliable)
            [[ "$remote_proto" == "udp" ]] && proto_flag="@"

            debug "Writing /etc/rsyslog.d/10-remote-forward.conf"
            mkdir -p /etc/rsyslog.d
            cat > /etc/rsyslog.d/10-remote-forward.conf <<EOF
# Remote syslog forwarding — generated by minix_z83_postinstall.sh
\$ActionQueueType        LinkedList
\$ActionQueueSize        10000
\$ActionQueueSaveOnShutdown off
\$ActionResumeRetryCount -1

*.* ${proto_flag}${remote_host}:${remote_port}
EOF
            echo "    [logging] Remote → ${remote_proto^^} ${remote_host}:${remote_port} configured."
        fi
    fi

    # ── 9b: USB-attached storage logging ────────────────────────────────────
    if confirm "  Configure logging to USB-attached storage?"; then
        if [[ -z "$usb_device" ]]; then
            echo ""
            echo "    Detected block devices:"
            lsblk -o NAME,SIZE,TYPE,MOUNTPOINT 2>/dev/null | grep -v loop || true
            echo ""
            read -r -p "    USB device path (e.g. /dev/sdb1): " usb_device
        fi

        if [[ -z "$usb_device" ]]; then
            echo "    No device entered — skipping USB logging."
        else
            do_usb=true
            [[ ! -b "$usb_device" ]] && \
                echo "    WARNING: $usb_device is not a recognised block device. Continuing anyway."

            debug "Creating mount point $usb_mount"
            mkdir -p "$usb_mount"

            if ! grep -q "$usb_device" /etc/fstab; then
                debug "Adding $usb_device to /etc/fstab (with snapshot)"
                fstab_begin
                # nofail: boot continues cleanly if the stick is absent
                echo "${usb_device}  ${usb_mount}  auto  defaults,noatime,nofail  0  0" >> /etc/fstab
                fstab_validate_or_rollback "USB log mount ($usb_device)"
                echo "    $usb_device → $usb_mount added to fstab (nofail, validated)."
            fi

            mount "$usb_device" "$usb_mount" 2>/dev/null \
                && echo "    Mounted $usb_device at $usb_mount." \
                || echo "    (Will mount on next boot — device may not be attached right now.)"

            debug "Writing /etc/rsyslog.d/20-usb-log.conf"
            cat > /etc/rsyslog.d/20-usb-log.conf <<EOF
# USB storage logging — generated by minix_z83_postinstall.sh
*.* ${usb_mount}/syslog.log
EOF
            echo "    [logging] USB → ${usb_mount}/syslog.log configured."
        fi
    fi

    # ── 9c: Disable local filesystem logging ────────────────────────────────
    if $do_remote || $do_usb; then
        echo ""
        echo "    A remote/USB log destination is active."

        local do_disable=false
        if [[ "$disable_local" == "true" ]]; then
            do_disable=true
        elif confirm "  Disable local filesystem logging entirely (recommended for eMMC)?"; then
            do_disable=true
        fi

        if $do_disable; then
            # Neutralise the default local-file ruleset shipped with rsyslog
            if [[ -f /etc/rsyslog.d/50-default.conf ]]; then
                debug "Renaming 50-default.conf → 50-default.conf.disabled"
                mv /etc/rsyslog.d/50-default.conf \
                   /etc/rsyslog.d/50-default.conf.disabled
                echo "    50-default.conf disabled — no local /var/log writes via rsyslog."
            fi

            # Tell journald to hand off to rsyslog rather than writing its own files.
            # Amend the conf written in Section 3d if it exists; create it otherwise.
            local jconf="/etc/systemd/journald.conf.d/99-emmc.conf"
            mkdir -p "$(dirname "$jconf")"
            if [[ -f "$jconf" ]]; then
                if ! grep -q 'ForwardToSyslog' "$jconf"; then
                    debug "Appending ForwardToSyslog=yes to $jconf"
                    echo "ForwardToSyslog=yes" >> "$jconf"
                fi
            else
                cat > "$jconf" <<'EOF'
[Journal]
Storage=volatile
RuntimeMaxUse=32M
Compress=yes
ForwardToSyslog=yes
EOF
            fi
            debug "Restarting systemd-journald"
            systemctl restart systemd-journald
            echo "    journald: Storage=volatile, ForwardToSyslog=yes."
        fi
    else
        echo "    No log destinations configured — local logging unchanged."
    fi

    # ── 9d: Restart rsyslog ──────────────────────────────────────────────────
    if $do_remote || $do_usb; then
        if systemctl list-unit-files 2>/dev/null | grep -q '^rsyslog.service'; then
            debug "Restarting rsyslog"
            systemctl restart rsyslog
            echo "    [logging] rsyslog restarted."
        else
            echo "    WARNING: rsyslog not found. Add 'rsyslog' to the PACKAGES array (Section 1)."
        fi
    fi

    echo "[logging] Done."
}

# ─────────────────────────────────────────────
# SECTION 9 — MOTIONEYE: pip bootstrap + install + verify
#
# Steps:
#   10a  Bootstrap pip via get-pip.py (skipped if pip3 already present)
#   10b  Configure /etc/pip.conf with break-system-packages=true
#   10c  pip install motioneye
#   10d  motioneye_init  (creates /etc/motioneye, /var/lib/motioneye, service)
#   10e  Verify the web UI answers on port 8765
# ─────────────────────────────────────────────
install_motioneye() {
    echo ""
    echo "=== SECTION 9: motionEye Installation ==="

    # ── 10a: Bootstrap pip ───────────────────────────────────────────────────
    echo "  [10a] Checking for pip3..."
    if command -v pip3 &>/dev/null; then
        echo "        pip3 already installed — skipping bootstrap."
    else
        debug "Downloading get-pip.py"
        curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
        debug "Running: python3 get-pip.py"
        python3 get-pip.py
        rm -f get-pip.py
        echo "        pip3 installed."
    fi

    # ── 10b: Configure /etc/pip.conf ────────────────────────────────────────
    echo "  [10b] Configuring /etc/pip.conf (break-system-packages=true)..."
    local pip_conf="/etc/pip.conf"

    # Add [global] section header if it doesn't exist
    if ! grep -q '^\[global\]' "$pip_conf" 2>/dev/null; then
        debug "Adding [global] header to $pip_conf"
        printf '[global]\n' | tee -a "$pip_conf" > /dev/null
    fi

    # Add break-system-packages only if not already present
    if ! grep -q 'break-system-packages' "$pip_conf" 2>/dev/null; then
        debug "Inserting break-system-packages=true under [global]"
        sed -i '/^\[global\]/a break-system-packages=true' "$pip_conf"
        echo "        break-system-packages=true written."
    else
        echo "        break-system-packages already set — skipping."
    fi

    # ── 10c: pip install motioneye ───────────────────────────────────────────
    echo "  [10c] Installing motionEye via pip..."
    debug "Running: python3 -m pip install motioneye"
    python3 -m pip install motioneye
    echo "        motionEye installed."

    # ── 10d: motioneye_init ──────────────────────────────────────────────────
    echo "  [10d] Running motioneye_init..."
    if command -v motioneye_init &>/dev/null; then
        debug "Running: motioneye_init"
        motioneye_init
        echo "        motioneye_init complete."
    else
        echo "  ERROR: motioneye_init not found after install — check pip output above." >&2
        return 1
    fi

    # ── 10e: Verify web UI on port 8765 ──────────────────────────────────────
    echo "  [10e] Verifying motionEye web UI on port 8765..."
    local local_ip
    local_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '/src/{print $7; exit}')
    [[ -z "$local_ip" ]] && local_ip=$(hostname -I 2>/dev/null | awk '{print $1}')

    local retries=10
    local delay=3
    local ok=false

    for ((i=1; i<=retries; i++)); do
        debug "Attempt $i/${retries}: curl http://${local_ip}:8765/"
        if curl -sSf --max-time 4 "http://${local_ip}:8765/" -o /dev/null 2>/dev/null; then
            ok=true
            break
        fi
        echo "        Waiting for motionEye to start... (${i}/${retries})"
        sleep "$delay"
    done

    if $ok; then
        echo ""
        echo "  ✔  motionEye web UI is up: http://${local_ip}:8765/"
    else
        echo ""
        echo "  WARNING: motionEye did not respond on http://${local_ip}:8765/ after $((retries * delay))s."
        echo "           Check: sudo systemctl status motioneye"
        echo "           Logs:  sudo journalctl -u motioneye -n 50"
    fi

    echo "[motioneye] Done."
}

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
echo "============================================"
echo " Minix Z83-4 Post-Install Configuration"
echo " $(date)"
echo "============================================"

# One acknowledgement covers every destructive change below.
show_change_summary

# Order is deliberate: anything that could brick the box (motionEye install,
# logging configuration) runs BEFORE disable_desktop so the machine remains
# recoverable via the GUI if something fails mid-run.
install_packages
additional_tweaks
configure_emmc
configure_audio
install_wifi_firmware
configure_cpu_governor
configure_grub_pstate
configure_logging
install_motioneye
disable_desktop      # MUST be last — everything above is verified first.

echo ""
echo "============================================"
echo " All sections complete."
echo "--------------------------------------------"
echo " Requires a reboot to fully apply:"
echo "   • Section 3b/3c — fstab (noatime, tmpfs mounts)"
echo "   • Section 6     — CPU governor at boot"
echo "   • Section 7     — GRUB / intel_pstate"
echo "   • Section 10    — headless boot target (multi-user.target)"
echo ""
echo " Already live (no reboot needed):"
echo "   • Sections 1, 2, 3a, 3d–3h, 4, 5, 8, 9"
echo ""
echo " Run transcript:  ${LOG_FILE}"
echo ""
echo " Reboot now:  sudo reboot"
echo "============================================"
